db:
  dsn: "root:root@tcp(localhost:13316)/ebook"

redis:
  addr: "localhost:16379"

test: "hello,babc"

kafka:
  addrs:
    - "localhost:9094"

grpc:
  client:
    intr:
      addr: "localhost:8090"
      secure: false
      threshold: 100