db:
  dsn: "root:root@tcp(localhost:13316)/ebook"

redis:
  addr: "localhost:16379"

test: "hello,babc"

kafka:
  addrs:
    - "localhost:9094"

grpc:
  client:
    intr:
      name: "interactive"
      secure: false

# 这个是流量控制的 client 的配置
#grpc:
#  client:
#    intr:
#      addr: "localhost:8090"
#      secure: false
#      threshold: 100

etcd:
  endpoints:
    - "localhost:12379"