// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"ebook/cmd/tag/grpc"
	"ebook/cmd/tag/repository/cache"
	"ebook/cmd/tag/repository/dao"
	"ebook/cmd/tag/service"
)

// Injectors from wire.go:

//go:generate wire
func InitGRPCService() *grpc.TagServiceServer {
	gormDB := InitTestDB()
	tagDAO := dao.NewGORMTagDAO(gormDB)
	cmdable := InitRedis()
	tagCache := cache.NewRedisTagCache(cmdable)
	logger := InitLogger()
	tagRepository := InitRepository(tagDAO, tagCache, logger)
	tagService := service.NewTagService(tagRepository, logger)
	tagServiceServer := grpc.NewTagServiceServer(tagService)
	return tagServiceServer
}
