// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package comment

import (
	"ebook/cmd/comment/grpc"
	"ebook/cmd/comment/ioc"
	"ebook/cmd/comment/repository"
	"ebook/cmd/comment/repository/dao"
	"ebook/cmd/comment/service"
	"ebook/cmd/pkg/appx"
	"github.com/google/wire"
)

// Injectors from wire.go:

//go:generate wire
func Init() *appx.App {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	commentDAO := dao.NewCommentDAO(db)
	commentRepository := repository.NewCommentRepo(commentDAO, logger)
	commentService := service.NewCommentSvc(commentRepository)
	commentServiceServer := grpc.NewCommentServer(commentService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxServer(commentServiceServer, client, logger)
	app := &appx.App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewCommentDAO, repository.NewCommentRepo, service.NewCommentSvc, grpc.NewCommentServer)

var thirdProvider = wire.NewSet(ioc.InitLogger, ioc.InitDB, ioc.InitEtcdClient)
