// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/stone/go_project/ebook/ebook/cmd/internal/repository/dao/user/user.go

// Package daomocks is a generated GoMock package.
package daomocks
