db:
  src:
    dsn: "root:root@tcp(localhost:13316)/ebook"
  dst:
    dsn: "root:root@tcp(localhost:13316)/ebook_intr"

redis:
  addr: "localhost:16379"

kafka:
  addrs:
    - "localhost:9094"

grpc:
  server:
    addr: ":8090"
#  client:
#    user:
#      addr: "user.mycompany.com:8090"
#    intr: