db:
  src:
    dsn: "root:root@tcp(localhost:13316)/ebook"
  dst:
    dsn: "root:root@tcp(localhost:13316)/ebook_interactive"

migrator:
  pattern: "SRC_ONLY"
  web:
    addr: ":8082"

redis:
  addr: "localhost:16379"

kafka:
  addrs:
    - "localhost:9094"

grpc:
  server:
    port: 8090
    etcdAddrs:
      - "localhost:12379"

#  client:
#    user:
#      addr: "user.mycompany.com:8090"
#    intr: