// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ebook/cmd/payment/grpc"
	"ebook/cmd/payment/handler"
	"ebook/cmd/payment/ioc"
	"ebook/cmd/payment/repository"
	"ebook/cmd/payment/repository/dao"
	"ebook/cmd/pkg/appx"
)

// Injectors from wire.go:

//go:generate wire
func InitApp() *appx.App {
	wechatConfig := ioc.InitWechatConfig()
	notifyHandler := ioc.InitWechatNotifyHandler(wechatConfig)
	client := ioc.InitWechatClient(wechatConfig)
	db := ioc.InitDB()
	paymentDAO := dao.NewPaymentGORMDAO(db)
	paymentRepository := repository.NewPaymentRepository(paymentDAO)
	logger := ioc.InitLogger()
	saramaClient := ioc.InitKafka()
	producer := ioc.InitProducer(saramaClient)
	nativePaymentService := ioc.InitWechatNativeService(client, paymentRepository, logger, producer, wechatConfig)
	wechatHandler := handler.NewWechatHandler(notifyHandler, nativePaymentService, logger)
	server := ioc.InitGinServer(wechatHandler)
	clientv3Client := ioc.InitEtcdClient()
	wechatServiceServer := grpc.NewWechatServiceServer(nativePaymentService)
	serverServer := ioc.InitGRPCServer(logger, clientv3Client, wechatServiceServer)
	app := &appx.App{
		WebServer:  server,
		GRPCServer: serverServer,
	}
	return app
}
