// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package sms

import (
	"ebook/cmd/pkg/appx"
	"ebook/cmd/sms/grpc"
	"ebook/cmd/sms/ioc"
)

// Injectors from wire.go:

//go:generate wire
func Init() *appx.App {
	service := ioc.InitSmsTencentService()
	smsServiceServer := grpc.NewSmsServiceServer(service)
	client := ioc.InitEtcdClient()
	logger := ioc.InitLogger()
	server := ioc.InitGRPCxServer(smsServiceServer, client, logger)
	app := &appx.App{
		GRPCServer: server,
	}
	return app
}
