// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ebook/cmd/oauth2/grpc"
	"ebook/cmd/oauth2/ioc"
	"ebook/cmd/pkg/appx"
	"github.com/google/wire"
)

// Injectors from wire.go:

//go:generate wire
func Init() *appx.App {
	logger := ioc.InitLogger()
	client := ioc.InitEtcdClient()
	service := ioc.InitPrometheus(logger)
	oauth2ServiceServer := grpc.NewOauth2ServiceServer(service)
	server := ioc.InitGRPCServer(logger, client, oauth2ServiceServer)
	app := &appx.App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitLogger, ioc.InitEtcdClient)
