// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"ebook/cmd/api/proto/gen/account/v1"
	"ebook/cmd/api/proto/gen/payment/v1"
	"ebook/cmd/reward/repository"
	"ebook/cmd/reward/repository/cache"
	"ebook/cmd/reward/repository/dao"
	"ebook/cmd/reward/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

//go:generate wire
func InitWechatNativeSvc(paymentClient pmtv1.WechatPaymentServiceClient, accountClient accountv1.AccountServiceClient) service.RewardService {
	gormDB := InitTestDB()
	rewardDAO := dao.NewRewardGORMDAO(gormDB)
	cmdable := InitRedis()
	rewardCache := cache.NewRewardRedisCache(cmdable)
	rewardRepository := repository.NewRewardRepository(rewardDAO, rewardCache)
	logger := InitLogger()
	rewardService := service.NewWechatNativeRewardService(paymentClient, accountClient, rewardRepository, logger)
	return rewardService
}

// wire.go:

var thirdPartySet = wire.NewSet(InitTestDB, InitLogger, InitRedis)
