// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/stone/go_project/ebook/ebook/cmd/cronjob/repository/types.go

// Package repomocks is a generated GoMock package.
package repomocks

import (
	context "context"
	domain "ebook/cmd/cronjob/domain"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCronJobRepository is a mock of CronJobRepository interface.
type MockCronJobRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCronJobRepositoryMockRecorder
}

// MockCronJobRepositoryMockRecorder is the mock recorder for MockCronJobRepository.
type MockCronJobRepositoryMockRecorder struct {
	mock *MockCronJobRepository
}

// NewMockCronJobRepository creates a new mock instance.
func NewMockCronJobRepository(ctrl *gomock.Controller) *MockCronJobRepository {
	mock := &MockCronJobRepository{ctrl: ctrl}
	mock.recorder = &MockCronJobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCronJobRepository) EXPECT() *MockCronJobRepositoryMockRecorder {
	return m.recorder
}

// AddJob mocks base method.
func (m *MockCronJobRepository) AddJob(ctx context.Context, j domain.CronJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddJob", ctx, j)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddJob indicates an expected call of AddJob.
func (mr *MockCronJobRepositoryMockRecorder) AddJob(ctx, j interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddJob", reflect.TypeOf((*MockCronJobRepository)(nil).AddJob), ctx, j)
}

// Preempt mocks base method.
func (m *MockCronJobRepository) Preempt(ctx context.Context) (domain.CronJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preempt", ctx)
	ret0, _ := ret[0].(domain.CronJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Preempt indicates an expected call of Preempt.
func (mr *MockCronJobRepositoryMockRecorder) Preempt(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preempt", reflect.TypeOf((*MockCronJobRepository)(nil).Preempt), ctx)
}

// Release mocks base method.
func (m *MockCronJobRepository) Release(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockCronJobRepositoryMockRecorder) Release(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockCronJobRepository)(nil).Release), ctx, id)
}

// Stop mocks base method.
func (m *MockCronJobRepository) Stop(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockCronJobRepositoryMockRecorder) Stop(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockCronJobRepository)(nil).Stop), ctx, id)
}

// UpdateNextTime mocks base method.
func (m *MockCronJobRepository) UpdateNextTime(ctx context.Context, id int64, next time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNextTime", ctx, id, next)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNextTime indicates an expected call of UpdateNextTime.
func (mr *MockCronJobRepositoryMockRecorder) UpdateNextTime(ctx, id, next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNextTime", reflect.TypeOf((*MockCronJobRepository)(nil).UpdateNextTime), ctx, id, next)
}

// UpdateUtime mocks base method.
func (m *MockCronJobRepository) UpdateUtime(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUtime", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUtime indicates an expected call of UpdateUtime.
func (mr *MockCronJobRepositoryMockRecorder) UpdateUtime(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUtime", reflect.TypeOf((*MockCronJobRepository)(nil).UpdateUtime), ctx, id)
}
