// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/stone/go_project/ebook/ebook/cmd/ranking/service/types.go

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	domain "ebook/cmd/ranking/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRankingService is a mock of RankingService interface.
type MockRankingService struct {
	ctrl     *gomock.Controller
	recorder *MockRankingServiceMockRecorder
}

// MockRankingServiceMockRecorder is the mock recorder for MockRankingService.
type MockRankingServiceMockRecorder struct {
	mock *MockRankingService
}

// NewMockRankingService creates a new mock instance.
func NewMockRankingService(ctrl *gomock.Controller) *MockRankingService {
	mock := &MockRankingService{ctrl: ctrl}
	mock.recorder = &MockRankingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankingService) EXPECT() *MockRankingServiceMockRecorder {
	return m.recorder
}

// RankTopN mocks base method.
func (m *MockRankingService) RankTopN(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RankTopN", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RankTopN indicates an expected call of RankTopN.
func (mr *MockRankingServiceMockRecorder) RankTopN(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RankTopN", reflect.TypeOf((*MockRankingService)(nil).RankTopN), ctx)
}

// TopN mocks base method.
func (m *MockRankingService) TopN(ctx context.Context) ([]domain.Article, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopN", ctx)
	ret0, _ := ret[0].([]domain.Article)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TopN indicates an expected call of TopN.
func (mr *MockRankingServiceMockRecorder) TopN(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopN", reflect.TypeOf((*MockRankingService)(nil).TopN), ctx)
}
