// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ebook/cmd/pkg/appx"
	"ebook/cmd/reward/grpc"
	"ebook/cmd/reward/ioc"
	"ebook/cmd/reward/repository"
	"ebook/cmd/reward/repository/cache"
	"ebook/cmd/reward/repository/dao"
	"ebook/cmd/reward/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

//go:generate wire
func Init() *appx.App {
	client := ioc.InitEtcdClient()
	wechatPaymentServiceClient := ioc.InitPaymentClient(client)
	accountServiceClient := ioc.InitAccountClient(client)
	db := ioc.InitDB()
	rewardDAO := dao.NewRewardGORMDAO(db)
	cmdable := ioc.InitRedis()
	rewardCache := cache.NewRewardRedisCache(cmdable)
	rewardRepository := repository.NewRewardRepository(rewardDAO, rewardCache)
	logger := ioc.InitLogger()
	rewardService := service.NewWechatNativeRewardService(wechatPaymentServiceClient, accountServiceClient, rewardRepository, logger)
	rewardServiceServer := grpc.NewRewardServiceServer(rewardService)
	server := ioc.InitGRPCxServer(rewardServiceServer, client, logger)
	app := &appx.App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitLogger, ioc.InitEtcdClient, ioc.InitRedis)
