// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ebook/cmd/cronjob/grpc"
	"ebook/cmd/cronjob/ioc"
	"ebook/cmd/cronjob/repository"
	"ebook/cmd/cronjob/repository/dao"
	"ebook/cmd/cronjob/service"
	"ebook/cmd/pkg/appx"
	"github.com/google/wire"
)

// Injectors from wire.go:

//go:generate wire
func Init() *appx.App {
	logger := ioc.InitLogger()
	client := ioc.InitEtcdClient()
	db := ioc.InitDB(logger)
	jobDAO := dao.NewGORMJobDAO(db)
	cronJobRepository := repository.NewPreemptCronJobRepository(jobDAO)
	cronJobService := service.NewCronJobService(cronJobRepository, logger)
	cronJobServiceServer := grpc.NewCronJobServiceServer(cronJobService)
	server := ioc.InitGRPCServer(logger, client, cronJobServiceServer)
	app := &appx.App{
		GRPCServer: server,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewGORMJobDAO, repository.NewPreemptCronJobRepository, service.NewCronJobService)

var thirdProvider = wire.NewSet(ioc.InitDB, ioc.InitLogger, ioc.InitEtcdClient)
