db:
  dsn: "root:root@tcp(localhost:13316)/ebook_article"

redis:
  addr: "localhost:6379"

kafka:
  addrs:
    - "localhost:9094"

etcd:
  endpoints:
    - "localhost:12379"
grpc:
  server:
    port: 8094
    etcdAddr: "localhost:12379"
    etcdTTL: 60
  client:
    user:
      target: "etcd:///service/user"