// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ebook/cmd/account/grpc"
	"ebook/cmd/account/ioc"
	"ebook/cmd/account/repository"
	"ebook/cmd/account/repository/dao"
	"ebook/cmd/account/service"
	"ebook/cmd/pkg/appx"
)

// Injectors from wire.go:

//go:generate wire
func Init() *appx.App {
	db := ioc.InitDB()
	accountDAO := dao.NewCreditGORMDAO(db)
	accountRepository := repository.NewAccountRepository(accountDAO)
	accountService := service.NewAccountService(accountRepository)
	accountServiceServer := grpc.NewAccountServiceServer(accountService)
	client := ioc.InitEtcdClient()
	logger := ioc.InitLogger()
	server := ioc.InitGRPCxServer(accountServiceServer, client, logger)
	app := &appx.App{
		GRPCServer: server,
	}
	return app
}
