// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ebook/cmd/im/events"
	"ebook/cmd/im/ioc"
	"ebook/cmd/im/service"
	"ebook/cmd/pkg/appx"
	"github.com/google/wire"
)

// Injectors from wire.go:

//go:generate wire
func Init() *appx.App {
	client := ioc.InitKafka()
	logger := ioc.InitLogger()
	secret := ioc.GetSecret()
	baseHost := ioc.GetBaseHost()
	httpClient := ioc.InitDefaultHttpClient()
	userService := service.NewRESTUserService(secret, baseHost, httpClient, logger)
	syncUserConsumer := events.NewSyncUserConsumer(client, logger, userService)
	v := ioc.NewConsumers(syncUserConsumer)
	app := &appx.App{
		Consumers: v,
	}
	return app
}

// wire.go:

var thirdProvider = wire.NewSet(ioc.InitKafka, ioc.InitLogger, ioc.GetSecret, ioc.GetBaseHost, ioc.InitDefaultHttpClient)
