// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"ebook/cmd/comment/grpc"
	"ebook/cmd/comment/repository"
	"ebook/cmd/comment/repository/dao"
	"ebook/cmd/comment/service"
	"ebook/cmd/pkg/logger/nop"
	"github.com/google/wire"
)

// Injectors from wire.go:

//go:generate wire
func InitGRPCServer() *grpc.CommentServiceServer {
	gormDB := InitTestDB()
	commentDAO := dao.NewCommentDAO(gormDB)
	logger := nop.NewNopLogger()
	commentRepository := repository.NewCommentRepo(commentDAO, logger)
	commentService := service.NewCommentSvc(commentRepository)
	commentServiceServer := grpc.NewCommentServer(commentService)
	return commentServiceServer
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewCommentDAO, repository.NewCommentRepo, service.NewCommentSvc, grpc.NewCommentServer)

var thirdProvider = wire.NewSet(nop.NewNopLogger, InitTestDB)
