// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"ebook/cmd/payment/ioc"
	"ebook/cmd/payment/repository"
	"ebook/cmd/payment/repository/dao"
	"ebook/cmd/payment/service/wechat"
	"github.com/google/wire"
)

// Injectors from wire.go:

//go:generate wire
func InitWechatNativeService() *wechat.NativePaymentService {
	wechatConfig := ioc.InitWechatConfig()
	client := ioc.InitWechatClient(wechatConfig)
	gormDB := InitTestDB()
	paymentDAO := dao.NewPaymentGORMDAO(gormDB)
	paymentRepository := repository.NewPaymentRepository(paymentDAO)
	logger := InitLogger()
	saramaClient := InitKafka()
	producer := NewSyncProducer(saramaClient)
	nativePaymentService := ioc.InitWechatNativeService(client, paymentRepository, logger, producer, wechatConfig)
	return nativePaymentService
}

// wire.go:

var thirdPartySet = wire.NewSet(InitLogger, InitTestDB, InitKafka)

var wechatNativeSvcSet = wire.NewSet(ioc.InitWechatClient, NewSyncProducer, dao.NewPaymentGORMDAO, repository.NewPaymentRepository, ioc.InitWechatNativeService, ioc.InitWechatConfig)
